type = "directrequest"
schemaVersion = 1
name = "player-bridge"
maxTaskDuration = "0s"
contractAddress = "0x9774be70A8f50b88A44e4C2C83E14C5a43364A6f"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="ea-id-bridge"]
    parse        [type=jsonparse path="data" data="$(fetch)"]
    encode_data  [type=ethabiencode abi="(bytes32 requestId,bytes _score)" data="{\\"requestId\\": $(decode_log.requestId),\\"_score\\": $(parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx    [type=ethtx to="0x9774be70A8f50b88A44e4C2C83E14C5a43364A6f" data="$(encode_tx)"]
    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""
